version: '2'
services:
  mysql:
    image: up2university/moodle-mysql:${GIT_BRANCH}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./envs:/envs
      - /data/moodle-mysql:/var/lib/mysql
  moodle:
    image: up2university/moodle:${GIT_BRANCH}
    restart: unless-stopped
    links:
      - mysql
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./envs:/envs
      - /data/letsencrypt:/etc/letsencrypt
      - /data/moodle-moodledata:/var/moodledata
